version: 0.2

env:
  variables:
    PYTHONUNBUFFERED: 1

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install aws-sam-cli
      - sam --version
  
  pre_build:
    commands:
      - echo "Validating SAM template..."
      - sam validate -t sam.yaml
  
  build:
    commands:
      - echo "Building SAM application..."
      - sam build -t sam.yaml --use-container
  
  post_build:
    commands:
      - echo "Packaging SAM application..."
      - sam package -t .aws-sam/build/template.yaml --s3-bucket $S3_ARTIFACT_BUCKET --output-template-file packaged.yaml
      - echo "Deploying SAM application..."
      - sam deploy --template-file packaged.yaml --stack-name ForexApiStack --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset

artifacts:
  files:
    - packaged.yaml
