version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install aws-sam-cli

  pre_build:
    commands:
      - echo "Preparing SAM build"
      - sam build -t Lambda-Athena-View/template.yaml

  build:
    commands:
      - echo "Deploying SAM application"
      - sam package -t .aws-sam/build/template.yaml --s3-bucket $S3_ARTIFACT_BUCKET --output-template-file template.yaml
      - echo "Deploying SAM application..."
      - sam deploy --template-file template.yaml --stack-name athena-table-lambda-stack --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset


artifacts:
  files:
    - template.yaml
