AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Forex API Lambda function

Resources:
  ForexLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: forex-lambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: . 
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          BUCKET_NAME: forexapiresults
          BUCKET_PREFIX: forex-Api-Results/
          CURRENCY_LIST: AUD,EUR
          SECRET_NAME: forex-api-key  # Only reference, not the actual key
      Policies:
        - S3WritePolicy:
            BucketName: forexapiresults
        - S3ReadPolicy:
            BucketName: forexapiresults
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:forex-api-key-*"
