env:
  variables:
    PYTHONUNBUFFERED: 1
    MY_BRANCH_NAME: "shilpa-lambda-New" 
    MY_GIT_USERNAME: "shilpa09-aws"       
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install aws-sam-cli
      - sam --version
 
      # Fetch full git history
      - echo "Fetching full git history..."
      - git fetch --all
 
      # Check if the latest commit 
      - echo "Checking if the latest commit was from $MY_GIT_USERNAME..."
      - LAST_AUTHOR=$(git log -1 --pretty=format:'%an')
      - echo "Last commit author: $LAST_AUTHOR"
      - |
        if [[ "$LAST_AUTHOR" == "$MY_GIT_USERNAME" ]]; then
          echo "Commit is from $MY_GIT_USERNAME. Proceeding with build..."
        else
          echo "Commit is not from $MY_GIT_USERNAME. Skipping build."
          exit 0
        fi
 
  pre_build:
    commands:
      - echo "Validating SAM template..."
      - sam validate -t sam.yaml
 
  build:
    commands:
      - echo "Building SAM application..."
      - sam build -t sam.yaml --use-container
 
  post_build:
    commands:
      - echo "Packaging SAM application..."
      - sam package -t .aws-sam/build/template.yaml --s3-bucket $S3_ARTIFACT_BUCKET --output-template-file packaged.yaml
      - echo "Deploying SAM application..."
      - sam deploy --template-file packaged.yaml --stack-name ForexApiStack --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset
 
artifacts:
  files:
    - packaged.yaml
 